name: Update

on:
  workflow_dispatch:

env:
  project-id: com.adilhanney.saber

jobs:
  update-flathub:
    name: Update Flathub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find latest tag
        run: |
          export LATEST_TAG=$(curl -s https://api.github.com/repos/adil192/saber/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')

      - name: Check if json needs updating
        run: |
          # Check if com.adilhanney.saber.json contains e.g. "adil192/saber/v0.5.5"
          if grep -q "adil192/saber/$LATEST_TAG" com.adilhanney.saber.json; then
            echo "com.adilhanney.saber.json is up to date"
            exit 1
          fi

      - name: Create a new branch
        run: |
          git checkout -b $LATEST_TAG

      - name: Hash Saber-Linux-Portable.tar.gz from adil192/saber
        run: |
          wget https://github.com/adil192/saber/releases/latest/download/Saber-Linux-Portable.tar.gz
          export ARCHIVE_HASH=$(sha256sum Saber-Linux-Portable.tar.gz | cut -d ' ' -f 1)

      - name: Hash com.adilhanney.saber.metainfo.xml from adil192/saber
        run: |
          wget https://raw.githubusercontent.com/adil192/saber/$LATEST_TAG/flatpak/com.adilhanney.saber.metainfo.xml
          export METAINFO_HASH=$(sha256sum com.adilhanney.saber.metainfo.xml | cut -d ' ' -f 1)

      - name: Update com.adilhanney.saber.json
        run: |
          # com.adilhanney.saber.metainfo.xml
          sed -i "s/\"url\": \"https:\/\/raw.githubusercontent.com\/adil192\/saber\/v[0-9]\.[0-9]\.[0-9]\/flatpak\/com.adilhanney.saber.metainfo.xml\", \"sha256\": \"[a-z0-9]\{64\}\"/\"url\": \"https:\/\/raw.githubusercontent.com\/adil192\/saber\/$LATEST_TAG\/flatpak\/com.adilhanney.saber.metainfo.xml\", \"sha256\": \"$METAINFO_HASH\"/g" com.adilhanney.saber.json
          # Saber-Linux-Portable.tar.gz
          sed -i "s/\"url\": \"https:\/\/github.com\/adil192\/saber\/releases\/download\/v[0-9]\.[0-9]\.[0-9]\/Saber-Linux-Portable.tar.gz\", \"sha256\": \"[a-z0-9]\{64\}\"/\"url\": \"https:\/\/github.com\/adil192\/saber\/releases\/download\/$LATEST_TAG\/Saber-Linux-Portable.tar.gz\", \"sha256\": \"$ARCHIVE_HASH\"/g" com.adilhanney.saber.json

      - name: Commit changes
        run: |
          git add com.adilhanney.saber.json
          git commit -m "Update com.adilhanney.saber.json to $LATEST_TAG"
          git push

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update com.adilhanney.saber.json to $LATEST_TAG
          title: Update com.adilhanney.saber.json to $LATEST_TAG
          body: |
            This pull request was automatically created by the GitHub Action `update.yaml`.
          branch: $LATEST_TAG
          delete-branch: true
          assignees: adil192
